"""Canonical machine-independent verifier for this repository."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def run(*args: str) -> None:
    subprocess.run(args, cwd=ROOT, check=True)


def main() -> None:
    run(sys.executable, "build_constraint_compression_leakage.py")
    run(sys.executable, "verify_constraint_compression_leakage.py")
    run(sys.executable, "build_repair_fixedpoint_gauge_descent.py")
    run(sys.executable, "verify_repair_fixedpoint_gauge_descent.py")
    run(sys.executable, "build_cohesive_repair_compression_transfer_comparison.py")
    run(sys.executable, "verify_cohesive_repair_compression_transfer_comparison.py")
    run(sys.executable, "build_selected_finite_weyl_koszul_hodge_and_interaction_cutset.py")
    run(sys.executable, "verify_selected_finite_weyl_koszul_hodge_and_interaction_cutset.py")
    run(sys.executable, "build_q79_weyl_koszul_monodromy_c4_cohomology_intertwiner.py")
    run(sys.executable, "verify_q79_weyl_koszul_monodromy_c4_cohomology_intertwiner.py")
    run(sys.executable, "build_q79_symmetric_weyl_calculus_isometric_retraction.py")
    run(sys.executable, "verify_q79_symmetric_weyl_calculus_isometric_retraction.py")
    run(sys.executable, "build_q79_signed_edge_first_jet_harmonic_ideal_quotient.py")
    run(sys.executable, "verify_q79_signed_edge_first_jet_harmonic_ideal_quotient.py")
    run(sys.executable, "build_q79_symmetric_response_retraction_transferred_m3.py")
    run(sys.executable, "verify_q79_symmetric_response_retraction_transferred_m3.py")
    run(sys.executable, "verify_q79_symmetric_response_transferred_m4.py")
    run(sys.executable, "build_q79_higher_transfer_jet_filtration_and_m5_feasibility.py")
    run(sys.executable, "verify_q79_higher_transfer_jet_filtration_and_m5_feasibility.py")
    run(sys.executable, "build_q79_all_arity_source_promotion.py")
    run(sys.executable, "verify_q79_all_arity_source_promotion.py")
    run(sys.executable, "build_q79_seven_row_endpoint_factorization.py")
    run(sys.executable, "verify_q79_seven_row_endpoint_factorization.py")
    run(sys.executable, "build_q79_bv4_associated_matter_externalization.py")
    run(sys.executable, "verify_q79_bv4_associated_matter_externalization.py")
    run(sys.executable, "build_provider_neutral_projection_source_quotient.py")
    run(sys.executable, "verify_provider_neutral_projection_source_quotient.py")
    run(sys.executable, "build_direct_one_constraint_multiplier_source.py")
    run(sys.executable, "verify_direct_one_constraint_multiplier_source.py")
    run(sys.executable, "build_closure_pressure_family_hessian_activation.py")
    run(sys.executable, "verify_closure_pressure_family_hessian_activation.py")
    run(sys.executable, "build_affine_zero_section_action.py")
    run(sys.executable, "verify_affine_zero_section_action.py")
    run(sys.executable, "build_normal_frame_action_intertwiner_reduction.py")
    run(sys.executable, "verify_normal_frame_action_intertwiner_reduction.py")
    run(sys.executable, "build_equivariant_feshbach_response.py")
    run(sys.executable, "verify_equivariant_feshbach_response.py")
    run(sys.executable, "build_weyl_gram_closure_repair_source.py")
    run(sys.executable, "verify_weyl_gram_closure_repair_source.py")
    run(sys.executable, "build_causal_weyl_gram_auxiliary_lift.py")
    run(sys.executable, "verify_causal_weyl_gram_auxiliary_lift.py")
    run(sys.executable, "build_relative_product_supercharge_source.py")
    run(sys.executable, "verify_relative_product_supercharge_source.py")
    run(sys.executable, "build_physical_yukawa_hessian_identification.py")
    run(sys.executable, "verify_physical_yukawa_hessian_identification.py")
    run(sys.executable, "build_upper_totalization_supercharge_selection.py")
    run(sys.executable, "verify_upper_totalization_supercharge_selection.py")
    run(sys.executable, "build_direct_finite_source_continuum_realization.py")
    run(sys.executable, "verify_direct_finite_source_continuum_realization.py")
    run(sys.executable, "build_direct_dirac_defect_repair_action.py")
    run(sys.executable, "verify_direct_dirac_defect_repair_action.py")
    run(sys.executable, "build_finite_dirac_spectral_action_classification.py")
    run(sys.executable, "verify_finite_dirac_spectral_action_classification.py")
    run(sys.executable, "build_finite_dirac_operator_repair_semigroup.py")
    run(sys.executable, "verify_finite_dirac_operator_repair_semigroup.py")
    run(sys.executable, "build_finite_dirac_cubic_variational_action.py")
    run(sys.executable, "verify_finite_dirac_cubic_variational_action.py")
    run(sys.executable, "build_ko6_fermionic_determinant_value_selection.py")
    run(sys.executable, "verify_ko6_fermionic_determinant_value_selection.py")
    run(sys.executable, "build_four_dimensional_fermion_determinant_scheme_classification.py")
    run(sys.executable, "verify_four_dimensional_fermion_determinant_scheme_classification.py")
    run(sys.executable, "build_product_dirac_joint_radial_source_modulus_action.py")
    run(sys.executable, "verify_product_dirac_joint_radial_source_modulus_action.py")
    run(sys.executable, "build_preprojection_finite_source_freeze_radial_values.py")
    run(sys.executable, "verify_preprojection_finite_source_freeze_radial_values.py")
    run(sys.executable, "build_same_root_state_repair_heat_profile_radial_values.py")
    run(sys.executable, "verify_same_root_state_repair_heat_profile_radial_values.py")
    run(sys.executable, "build_frozen_source_four_dimensional_fermion_pushforward.py")
    run(sys.executable, "verify_frozen_source_four_dimensional_fermion_pushforward.py")
    run(sys.executable, "build_pointed_closure_germ_quantum_jet_matching.py")
    run(sys.executable, "verify_pointed_closure_germ_quantum_jet_matching.py")
    run(sys.executable, "build_quantum_radial_anchor_tadpole.py")
    run(sys.executable, "verify_quantum_radial_anchor_tadpole.py")
    run(sys.executable, "build_radial_closure_attractor_state_marginal.py")
    run(sys.executable, "verify_radial_closure_attractor_state_marginal.py")
    run(sys.executable, "build_renormalized_bv_anchored_repair_semiflow.py")
    run(sys.executable, "verify_renormalized_bv_anchored_repair_semiflow.py")
    run(sys.executable, "build_source_preserving_pointed_quantum_projection.py")
    run(sys.executable, "verify_source_preserving_pointed_quantum_projection.py")
    run(sys.executable, "build_cotangent_lifted_local_formal_projection.py")
    run(sys.executable, "verify_cotangent_lifted_local_formal_projection.py")
    run(sys.executable, "build_shared_circle_morse_bott_rank_four.py")
    run(sys.executable, "verify_shared_circle_morse_bott_rank_four.py")
    run(sys.executable, "build_weyl_polarized_product_dirac_g0.py")
    run(sys.executable, "verify_weyl_polarized_product_dirac_g0.py")
    run(sys.executable, "build_causal_relative_cauchy_evolution_global_g0.py")
    run(sys.executable, "verify_causal_relative_cauchy_evolution_global_g0.py")
    run(sys.executable, "build_future_cone_spectral_polarization.py")
    run(sys.executable, "verify_future_cone_spectral_polarization.py")
    run(sys.executable, "build_selected_future_state_moller_bv_transport.py")
    run(sys.executable, "verify_selected_future_state_moller_bv_transport.py")
    run(sys.executable, "build_selected_gauge_physical_future_state.py")
    run(sys.executable, "verify_selected_gauge_physical_future_state.py")
    run(sys.executable, "build_selected_radial_higgs_future_state.py")
    run(sys.executable, "verify_selected_radial_higgs_future_state.py")
    run(sys.executable, "build_common_action_quantum_torsor.py")
    run(sys.executable, "verify_common_action_quantum_torsor.py")
    run(sys.executable, "build_normalized_orientation_coframe_bv_bridge.py")
    run(sys.executable, "verify_normalized_orientation_coframe_bv_bridge.py")
    run(sys.executable, "build_q79_oriented_hodge_real_carrier.py")
    run(sys.executable, "verify_q79_oriented_hodge_real_carrier.py")
    run(sys.executable, "build_q79_hermitian_metric_hodge_compiler.py")
    run(sys.executable, "verify_q79_hermitian_metric_hodge_compiler.py")
    run(sys.executable, "build_same_source_principal_symbol_metric_hodge_naturality.py")
    run(sys.executable, "verify_same_source_principal_symbol_metric_hodge_naturality.py")
    run(sys.executable, "build_dirac_dolbeault_principal_symbol_bridge.py")
    run(sys.executable, "verify_dirac_dolbeault_principal_symbol_bridge.py")
    run(sys.executable, "build_augmented_heterotic_triangular_principal_symbol.py")
    run(sys.executable, "verify_augmented_heterotic_triangular_principal_symbol.py")
    run(sys.executable, "build_full_graded_augmented_heterotic_symbol_parametrix.py")
    run(sys.executable, "verify_full_graded_augmented_heterotic_symbol_parametrix.py")
    run(sys.executable, "build_augmented_hodge_lower_order_inverse_tail_compiler.py")
    run(sys.executable, "verify_augmented_hodge_lower_order_inverse_tail_compiler.py")
    run(sys.executable, "build_q79_fourier_mukai_double_qutrit_augmented_exterior_bridge.py")
    run(sys.executable, "verify_q79_fourier_mukai_double_qutrit_augmented_exterior_bridge.py")
    run(sys.executable, "build_q79_double_qutrit_mixed_bidegree_spinc_soldering.py")
    run(sys.executable, "verify_q79_double_qutrit_mixed_bidegree_spinc_soldering.py")
    run(sys.executable, "build_q79_binary_spinc_pauli_rootstack_compiler.py")
    run(sys.executable, "verify_q79_binary_spinc_pauli_rootstack_compiler.py")
    run(sys.executable, "build_q79_eta9_cayley_serre_trace_normalization.py")
    run(sys.executable, "verify_q79_eta9_cayley_serre_trace_normalization.py")
    run(sys.executable, "verify_q79_b89_accelerated_source_isotopy.py")
    run(sys.executable, "verify_q79_b89_source_isotopy_frontier_freeze.py")
    run(sys.executable, "build_q79_b89_downstream_promotion_readiness.py")
    run(sys.executable, "verify_q79_b89_downstream_promotion_readiness.py")
    run(sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v")
    print("repository verification passed")


if __name__ == "__main__":
    main()
